graph LR
    A[Median Imputation]
    B[Logistic Regression with L1 Regularization Feature Selection, and observe removed features]
    C["Extra Trees Classifier (Ensemble Decision Trees)"]

    A --> B
    B --> C

